### PR TITLE
Improve fonts generation: remove Math-Regular font

### PR DESCRIPTION
**Pull request by ylemkimon**
This PR is part of #12 and https://github.com/Khan/KaTeX/issues/1250.

Math-Regular is identical to Math-Italic in KaTeX font generation and not used in the KaTeX.

### CODE REVIEW

**Comment by edemaine** [comment]
OK, next question: how do we implement italic/non-italic Greek letters if not via Regular/Italic?

**Comment by ylemkimon** [comment]
@edemaine Upright Greek letters are in `Main-Regular` and italic ones are in `Math-Italic`.

**Comment by kevinbarabash** [comment]
@ylemkimon can you open a KaTeX PR that uses these changes so that we can test them?  I think this is a really good argument for having font creation live within the main KaTeX repo.  Before we do that though, I'd like to do https://github.com/KaTeX/katex-fonts/issues/15.

**Comment by ylemkimon** [comment]
@kevinbarabash I updated https://github.com/Khan/KaTeX/pull/1494.

**Comment by kevinbarabash** [comment]
I think we should wait until #54 is merged.

**Comment by ylemkimon** [comment]
Closing in favor of #56.

**Pull request closed without merging**
