### PR TITLE
add Greek-Italic font and update LICENSE file

### LINKED ISSUE #7: Add italic capital Greek letters
AMS defines these macros for italic capital Greek letters:
```latex
\varGamma
\varDelta
\varTheta
\varLambda
\varXi
\varPi
\varSigma
\varUpsilon
\varPhi
\varPsi
\varOmega
```
These are the remaining characters (I believe) needed for https://github.com/Khan/KaTeX/issues/130

### PR DESCRIPTION
**Pull request by kevinbarabash**
I stumble across a MathJax copyright notice in one of the Makefile so I thought I'd call it out in the our LICENSE file.

I was thinking the Greek-Italic fonts could provide an alternate solution to https://github.com/Khan/KaTeX/issues/1077.  Not sure if it's better though as it means clients will have to load yet another font file.

Fixes #7.

### CODE REVIEW

**Comment by kevinbarabash** [comment]
Greek fonts were removed in https://github.com/Khan/KaTeX/pull/184.  It doesn't give much of an explanation as to why.

**Comment by edemaine** [comment]
Is there a good reason to make a separate Greek font that contains these 20ish characters, versus using existing font structure, e.g., Main-Italic for italic Greek and Main-Regular for roman Greek?  I'm guessing the answer is "this is how MathJax did/does it", but it makes less logical sense... of course, this may require some refactoring on the KaTeX side, but wouldn't be too hard.

**Comment by kevinbarabash** [comment]
> Is there a good reason to make a separate Greek font that contains these 20ish characters

The more I think about, the answer is: no.

**Comment by kevinbarabash** [comment]
@edemaine what do you think of my initial suggestion of using macros to implement `\varGamma`, etc.?

**Comment by edemaine** [comment]
Oh, so the characters are already there! Yes, https://github.com/Khan/KaTeX/issues/1077 seems like a good way to go.

**Comment by edemaine** [comment]
@kevinbarabash Do you want to preserve the copyright tweak in another PR?

**Comment by kevinbarabash** [comment]
Yeah, I'll open a new PR.

**Pull request closed without merging**
