### PR TITLE
Improve fonts generation: remove unused codes

### PR DESCRIPTION
**Pull request by ylemkimon**
This PR is part of #12.

- Remove CSS generation: CSS is generated by `fonts.less`
- Remove EOT and SVG font generation
  - EOT was removed in #8 
  - SVG was never used. In fact, SVG generation never worked since dependencies were not installed
  - Both font types are not needed in browsers that is supported by KaTeX
- Remove skew data generation: skew data was never used
- Remove Greek and Windows fonts: they were never used
- Remove `install` target: copying font files is handled by `buildFonts.sh`
- Remove `fonts` and `pack` target in `src/Makefile`
- Remove unused dependencies and variables

### CODE REVIEW

**Comment by ylemkimon** [comment]
@edemaine This seems to break `\not`: https://circleci.com/workflow-run/834d152e-6f1b-4fbd-9628-34b4189b3740. But I'm not sure what's causing it.

**Comment by edemaine** [comment]
I haven't looked at this yet, but what do you mean by "skew generation isn't used"?  Don't we need this for italic correction/spreading out (in `\mathit`)?

**Comment by kevinbarabash** [comment]
@ylemkimon the `katex-fonts` submodule is at `c5fe193` in the `Khan/KaTeX` repo, but `katex-fonts/master` is at `e641de5`.  It's probably my fault that `\not` is broken.

**Comment by kevinbarabash** [comment]
The problem is that I didn't realize that right bearings on the `\not` glyph were modified elsewhere.  Not sure why this issue didn't show up during manual testing.

This highlights one of the downsides of using a submodule for the font.  There isn't a good way to test changes automatically.  We may want to look at moving font creation into the main repo at some point to address this deficiency.

**Comment by kevinbarabash** [comment]
@ylemkimon this is awesome!  Thanks for starting to simplify font creation.

**Comment by ylemkimon** [comment]
@edemaine We have different method of calculating skew in metrics generation.

**Comment by ylemkimon** [comment]
@kevinbarabash Of course, tests fail because https://github.com/Khan/KaTeX/pull/1267 was not merged. Why didn't I think of that before 😄

**Comment by ylemkimon** [comment]
@kevinbarabash https://github.com/KaTeX/katex-fonts/blob/e641de5365c12742fe71f89ed74f093e173c7c19/src/metrics/extract_tfms.py#L96-L100

**Comment by ylemkimon** [comment]
I think we can remove TTF font format too. I've created an issue at the main repo, https://github.com/Khan/KaTeX/issues/1495.

**Comment by ylemkimon** [comment]
BTW, I wonder why `woff` and `woff2` generations are not done using FontForge.

**Comment by edemaine** [comment]
Another question: Should we support SVG fonts? This seems relevant to KaTeX one day supporting SVG output (https://github.com/Khan/KaTeX/issues/375).

Ah, never mind: [SVG fonts seem to have poor support in general](https://developer.mozilla.org/en-US/docs/Web/SVG/Tutorial/SVG_fonts), e.g., support for them was removed from Chrome.  SVG can use any CSS-accessible fonts, at least in the browser.

**Comment by ylemkimon** [comment]
This PR does not change contents of fonts. (Checked with `ttx`)

**Comment by ylemkimon** [comment]
@edemaine Without #54, font binaries will change due to timestamps. Yes, it is possible dump the font file to XML using `ttx` and compare them.

**Pull request merged**
